version: '3.9'
services:
  web:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - ${APP_PORT}:9000
    networks:
      - default
    volumes:
      - data:/data

networks:
  default:
    driver: bridge
  services_net:
      driver: bridge
      ipam:
          config:
              - subnet: 192.168.1.0/24
                gateway: 192.168.1.1

volumes:
  data:
    driver: local
